source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

use_frameworks!
def shared_pods
    pod 'Charts', '>= 2.2.4'
    pod 'Alamofire', '~>3.3'
    pod 'ColorizeSwift'
    pod 'paper-onboarding'
end
def test_pods 
    pod 'Fakery'
end

target 'app-steady' do
    shared_pods
end

target 'app-steadyTests' do
    shared_pods
    test_pods
end

